name: tool_base
description: Base for developing command line apps. Take from Flutter Tools.
version: 2.0.0
homepage: https://github.com/mmcc007/tool_base

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.1.2
  file: ^6.1.2
  intl: ^0.17.0
#  platform: ^2.2.0
  process: ^4.2.3
  pub_cache: ^0.3.1

dev_dependencies:
  build_runner: ^2.0.0
  file_testing: ^3.0.0
  mockito: ^5.0.16
  lints: ^1.0.1
  quiver: ^3.0.0
  test: ^1.19.2
